### ISSUE TITLE
feat: add basic blog functionality

### ISSUE THREAD

**Issue by elianiva** [teknologi-umum/blog#1]
Shouldn't be that hard. 

- Use http://mdsvex.com/ instead of regular markdown
- Use https://github.com/svelte-add/svelte-add if you want an easier route
- Create /blog route filled with .svx files
- Don't worry about making it look good, we need the functionality first

See [this repo](https://github.com/elianiva/elianiva.my.id) for reference

**Comment by aldy505** [comment]
isn't that would be easier for people to write on .md extension instead of .svx?

**Comment by elianiva** [comment]
> isn't that would be easier for people to write on .md extension instead of .svx?

extensionnya bisa diganti jadi .md kok, tapi tetep pake mdsvex
