### ISSUE TITLE
view post by category got error

### ISSUE THREAD

**Issue by WahidinAji** [teknologi-umum/blog#109]
this's what the browser console said
![image](https://user-images.githubusercontent.com/48281037/183411396-c0cea319-9bd2-436e-9d5e-832b6b925136.png)

and this's the errors
![image](https://user-images.githubusercontent.com/48281037/183411516-7fe8655d-5bf4-4253-be61-40a23f79ded1.png)

**Comment by elianiva** [comment]
#110
