### ISSUE TITLE
fix article card height

### ISSUE THREAD

**Issue by elianiva** [teknologi-umum/blog#116]
Currently the post card displayed is uneven. This is because there are different amount of topic badges. Ideally they should all have the same height.

Several possible solutions:
- limit the topic badges, eg: max 2 badges for each post card
- make the card height to be the same, although the result may look awkward since there will be too much empty space
- make the topic badges horizontally scrollable
- etc

![image](https://user-images.githubusercontent.com/51877647/193439214-247eaa5c-e828-4a69-8045-75353c3dfb79.png)

**Comment by Abdirizaks12** [comment]
assign this to me

**Comment by c-shubh** [comment]
I'll take this up. @elianiva please assign me this issue.
