### ISSUE TITLE
change favicon to teknum's

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/blog#66]
see https://github.com/teknologi-umum/analytics/issues/2

cc @elianiva @lamualfa

**Comment by herlangga72** [comment]
le-rocket or the logo one ?
and are you want to make it PWA standard too ?

**Comment by elianiva** [comment]
> le-rocket or the logo one ? and are you want to make it PWA standard too ?

yg logo, bentuknya kek roket

**Comment by herlangga72** [comment]
closed @aldy505

**Comment by aldy505** [comment]
oh iya lupa, thanks pak @herlangga72
