### ISSUE TITLE
bug: Responsive layout problem when width <= 375px

### ISSUE THREAD

**Issue by ronnygunawan** [teknologi-umum/blog#73]
How to reproduce:
Screen width <= 375px. the smaller the better.

![photo_2022-01-01_15-25-54](https://user-images.githubusercontent.com/3048897/147846866-7a978384-871d-4cf7-bbc4-4bd4a8d5aa27.jpg)

**Comment by herlangga72** [comment]
Oke wait ane selidiki

**Comment by herlangga72** [comment]
Apa karena bump ke tw 3 ya ?entar ane rollback and check. Entar malem ane coba selesaiin
